services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build:
      context: ./Backend/TodoApp/TodoApp
      dockerfile: ../Dockerfile
    container_name: todo-backend
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskDb;User=sa;Password=Your_password123;
    depends_on:
      - sqlserver

  frontend:
    build:
      context: ./Frontend/todo-app
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  sql_data: